alias iCompApi-up='systemctl start iCompApi'
alias iCompApi-down='systemctl stop iCompApi'
alias iCompApi-stat='systemctl status iCompApi'
alias iCompApi-showLogs='ls -la /var/log/iComp/'
alias iCompDB-schema='python3 /usr/local/lib/iCompetition/python/scripts/displaySchema.py'
alias iCompDB-version='python3 /usr/local/lib/iCompetition/python/scripts/displayICompVersion.py'