alias iCompApi-up='systemctl start iCompApi'
alias iCompApi-down='systemctl stop iCompApi'
alias iCompApi-stat='systemctl status iCompApi'
alias iCompApi-showLogs='ls -la /var/log/iComp/'
alias iCompApi-followApiLog='tail -f /var/log/iComp/api.log'
alias iCompApi-followGunicornLog='tail -f /var/log/iComp/gunicorn.log'
alias iCompDB-schema='python3 /usr/local/lib/iCompetition/python/scripts/displaySchema.py'