alias iCompApi-up='systemctl start iCompApi'
alias iCompApi-down='systemctl stop iCompApi'
alias iCompApi-stat='systemctl status iCompApi'
alias iCompApi-showLogs='ls -la /var/log/iComp/'
alias iComp-version='python3 /usr/local/lib/iCompetition/python/scripts/displayICompVersion.py'